config/routes.rb
Getup::Application.routes.draw do

  get "people/index"
  post "people/index"

  root :to => "people#index"

end

app/models/people.rb
class People < ActiveRecord::Base
  belongs_to :postcode

  class << self

    def email_domains
      #TODO memcache?
      People.select(:email_domain).group(:email_domain).order(:email_domain)
    end

    # sanitise the email array for use in db query
    def sanitise_email(email)
      if email.nil?
        return nil
      end

      email.length.times do |i|
        email[i] = email[i].gsub(/[^\w]/,'') #remove all non-word chars
      end
      return email
    end

    #sanitise the postcode array for use in db query
    def sanitise_postcode(postcode)
      if postcode.nil?
        return nil
      end

      postcode.length.times do |i|
        postcode[i] = postcode[i].gsub(/[^\d]/, '') #remove all non-numeric chars
      end
      return postcode
    end

    # perform search for people based on email or postcode
    def do_search(email_option, email, postcode_option, postcode)
      email = sanitise_email(email)
      postcode = sanitise_postcode(postcode)

      query = People.joins(:postcode)
      if(email_option == 'include' && email )
        query = query.where(:email_domain => email)
      elsif(email_option == 'exclude' && email )
        query = query.where("email_domain NOT IN (?)", email)
      end

      if(postcode_option == 'include' && postcode)
        query = query.where(:postcodes => {:number => postcode})
      elsif(postcode_option == 'exclude' && postcode)
        query = query.where("postcodes.number NOT in (?)", postcode )
      end

      return query.order(:name).all
    end
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :postcode

  class << self

    def email_domains
      #TODO memcache?
      Person.select(:email_domain).group(:email_domain).order(:email_domain)
    end

    # sanitise the email array for use in db query
    def sanitise_email(email)
      return nil if email.blank?
      #remove all non-word chars
      email.collect{ |e| e.gsub(/[^\w]-/,'')}
      return email
    end

    #sanitise the postcode array for use in db query
    def sanitise_postcode(postcode)
      return nil if postcode.blank?
      #remove all non-numeric chars
      postcode.collect{ |p| p.to_s.gsub(/[^\d]/, '')}
      return postcode
    end

    # perform search for people based on email or postcode
    def search(email_option, email, postcode_option, postcode)
      email = sanitise_email(email)
      postcode = sanitise_postcode(postcode)

      query = Person.joins(:postcode)
      if(email_option == 'include' && email )
        query = query.where(:email_domain => email)
      elsif(email_option == 'exclude' && email )
        query = query.where("email_domain NOT IN (?)", email)
      end

      if(postcode_option == 'include' && postcode)
        query = query.where(:postcodes => {:number => postcode})
      elsif(postcode_option == 'exclude' && postcode)
        query = query.where("postcodes.number NOT in (?)", postcode )
      end

      return query.order(:name).all
    end
  end
end

app/models/postcode.rb
class Postcode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index

    @postcodes = Postcode.all
    @email_domains = Person.email_domains

    if(params[:email_option] || params[:postcode_option])
      @people = Person.search(params[:email_option], params[:email], params[:postcode_option], params[:postcode])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getup</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<h1>Search</h1>

<%= form_tag( people_index_path , {:method => "get", :id => "search-form"})  do -%>

    <%= field_set_tag 'email' do -%>
        Include: <%= radio_button_tag :email_option, :include, true %>
        Exclude: <%= radio_button_tag :email_option, :exclude %><br/>

        <%= select_tag "email", options_from_collection_for_select(@email_domains, "email_domain", "email_domain"), {:multiple => true, :size => 5} %>
    <% end -%>

    <%= field_set_tag 'postcode' do -%>
        Include: <%= radio_button_tag :postcode_option, :include, true %>
        Exclude: <%= radio_button_tag :postcode_option, :exclude %><br/>

        Postcodes:
        <%= select_tag "postcode", options_from_collection_for_select(@postcodes, "number", "number"), {:multiple => true, :size => 5} %>
    <% end -%>

    <%= submit_tag "Search", :id => "search-button" %>
<% end -%>

app/views/people/_results.html.erb
<h1>Results</h1>


<table>
  <tr><th>Name</th><th>Postcode</th><th>Email</th></tr>
<% for person in @people %>
      <tr><td><%= person.name %></td><td><%= person.postcode.number %></td><td><%= person.email %></td></tr>
<% end %>
</table>

app/views/people/index.html.erb
<%= render :partial => 'form' %>

<% if @people %>
    <%= render :partial => 'results', :object => @results %>
<% end %>